### ISSUE TITLE
Create my own training data

### ISSUE THREAD

**Issue by jian3xiao** [avanetten/simrdwn#10]
I have some questions about training data. 
I have satellite imagery which is tif format. And in 1A Create YOLT format said 'training data needs to be transformed to the YOLO format'. I know the YOLO format (also faster rcnn) is .jpg images and .xml labels. But how I transform my tif satellite imagery into jpg image?
The tif satellite imagery is 48 bit depth, but my transformed jpg image is 24 bit depth which is blur. 
Thanks a lot !

**Comment by avanetten** [comment]
Take a look at https://github.com/avanetten/simrdwn/blob/master/core/prep_data_cowc.py, hopefully this will provide everything you need to prepare training data.
