### ISSUE TITLE
What's the format of the training_images_list and how can I generate it?

### ISSUE THREAD

**Issue by ash1995** [avanetten/simrdwn#11]
I have tiled jpg images and the corresponding annotations. How can I generate the training_list.txt? As I understand it is a list of the images and their locations. So is it of the format

Name              Location

img1.jpg                path/to/img1
img2.jpg                path/to/img2

If this is indeed the format, I could manually generate it.

**Comment by avanetten** [comment]
Check out https://github.com/avanetten/simrdwn/blob/master/core/prep_data_cowc.py, line 166:

##############################
# Get list for simrdwn/data/, copy to data dir
##############################
train_ims = [os.path.join(images_dir, f) for f in  os.listdir(images_dir)]
f = open(im_list_name, 'wb')
for item in train_ims:
    f.write("%s\n" % item)
f.close()
# copy to data dir
shutil.copy(im_list_name, simrdwn_data_dir)
##############################
