### ISSUE TITLE
Nan problems during training

### ISSUE THREAD

**Issue by ash1995** [avanetten/simrdwn#13]
I'm having a possible gradient issue while training. When training on batches the following prompt comes up:

Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.463884, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.463872, Avg Recall: -nan,  count: 0
Region Avg IOU: -nan, Class: -nan, Obj: -nan, No Obj: 0.463883, Avg Recall: -nan,  count: 0
....

Does anyone how to rectify it?

**Comment by SheInk** [comment]
I am stuck with the same issue, anything?

**Comment by avanetten** [comment]
What are the input image sizes you are training on?  Sometimes inputs that are too large can give this error.

**Comment by ash1995** [comment]
My images are of size 900 x 900 pixels

**Comment by avanetten** [comment]
My guess would be an issue related to the label format, but I can't be sure without more information.

**Comment by ash1995** [comment]
My labels are of the `class_id  <x_center> <y_center> <width> <height>` format:

1 0.876977 0.555887 0.074074 0.042762
1 0.974364 0.451216 0.052320 0.040534
1 0.870561 0.447706 0.133511 0.036080
1 0.883241 0.374917 0.086092 0.034906
1 0.975940 0.373796 0.048898 0.031485

**Comment by avanetten** [comment]
I will have a better chance of helping if you can also provide the command you're using to begin training.  One further possibility is that the labels need to be zero-indexed, so if you only have a single object class the labels should appear as:
0 0.876977 0.555887 0.074074 0.042762
0 0.974364 0.451216 0.052320 0.040534
0 0.870561 0.447706 0.133511 0.036080
0 0.883241 0.374917 0.086092 0.034906
0 0.975940 0.373796 0.048898 0.031485

**Comment by ash1995** [comment]
You were right. The problem was due to the class labelling not being zero indexed. Thanks.
