### ISSUE TITLE
Running on gpu within docker

### ISSUE THREAD

**Issue by ash1995** [avanetten/simrdwn#14]
I copied over the simrdwn folder into the docker container and set it up as per the instructions provided. However, I've noticed that running the following train command in the docker container does not use the gpu, and as such each iteration takes about an hour to complete.

```
# YOLT vehicle search
python /simrdwn/core/simrdwn.py \
	--framework yolt \
	--mode train \
	--outname dense_3class_vehicles \
	--yolt_object_labels_str tmp0,airplane,boat,car \
	--yolt_cfg_file ave_dense.cfg  \
	--weight_dir /simrdwn/yolt/input_weights \
	--weight_file yolo.weights \
	--yolt_train_images_list_file labels_airplane_boat_car_list.txt \
	--label_map_path /simrdwn/data/class_labels_airplane_boat_car.pbtxt \
	--nbands 3 \
	--max_batches 30000 \
	--batch_size 64 \
	--subdivisions 16 \
	--gpu 0
```

How can I run the program within the container using a gpu?

**Comment by slilxn** [comment]
Was your darknet built with GPU enabled? There is a flag in the Makefile where the first line dictates if GPU is used, I guess.

**Comment by avanetten** [comment]
The flags at the top of YOLT Makefile determine whether to use the GPU.  The updated Makefile (https://github.com/avanetten/simrdwn/blob/master/yolt/Makefile) now defaults to GPU use.
