### ISSUE TITLE
Training not starting on latest code

### ISSUE THREAD

**Issue by Raj800** [avanetten/simrdwn#19]
The code gets stuck over here:

_Loading weights from /home/raj/Desktop/codes/simrdwn/yolt/input_weights/yolov2.weights...label i: 0, airplane

Done!
Learning Rate: 0.0001, Momentum: 0.9, Decay: 0.0005

Num images = 64,
i= 0
N ims: 1
Num iters: 30000_

 
After which, nothing happens

**Comment by avanetten** [comment]
It looks like your list of training images has length 1, given that "N ims: 1".  You'll need more than one training image for a model to converge.

**Comment by Raj800** [comment]
Similar issue with a larger dataset. Darknet is not starting. I checked that in Nvidia smi as well as system monitor.

_Loading weights from /home/raj/Desktop/codes/simrdwn/yolt/input_weights/yolov2.weights...label i: 0, airplane
Done!
Learning Rate: 0.0001, Momentum: 0.9, Decay: 0.0005

Num images = 64,
i= 0
N ims: 8000
Num iters: 30000_

**Comment by avanetten** [comment]
I recommend checking to see if version 2 (recently uploaded) fixes this problem.

**Comment by alexteua** [comment]
Same issue here:

Num images = 64,
i= 0
N ims: 2824
Num iters: 10
Loaded: 1.517870 seconds
Batch Num: 1 / 10

After this nothing is happening. Tried different configurations, with both yolt2 and yolt3.

**Comment by alexteua** [comment]
I fixed with solution from this issue
https://github.com/avanetten/simrdwn/issues/79
