### ISSUE TITLE
Can i used other datasets to train simrdwn?

### ISSUE THREAD

**Issue by 51616** [avanetten/simrdwn#22]
I tried to import and format SpaceNet building data using official utilities but failed horribly.
Is there any code from legacy project of yours that implemented SIMRDWN on SpaceNet dataset?
Can I see the code or can i work around the code in this repo (change from cocw to SpaceNet)?

**Comment by avanetten** [comment]
You should be able to adapt code from https://github.com/avanetten/spacenet_buildings_exploration and parse_cowc.py to train on SpaceNet buildings.
