### ISSUE TITLE
Evaluation Result not displayed

### ISSUE THREAD

**Issue by ash1995** [avanetten/simrdwn#23]
I used the following command to test the trained model on two test images. 
`python simrdwn/core/simrdwn.py 
--framework yolt 
--mode valid 
--outname dense_buildings 
--yolt_object_labels_str building 
--train_model_path train_yolt_dense_buildings_2019_01_16_07-05-19 
--weight_file ave_dense_20000_tmp.weights 
--yolt_cfg_file ave_dense.cfg 
--valid_testims_dir test_images2  
--use_tfrecords 0 
--min_retain_prob=0.15 
--keep_valid_slices 0 
--slice_overlap 0.1 
--slice_sizes_str 544 
--valid_slice_sep __ 
--plot_thresh_str 0.2 
--valid_make_legend_and_title 0 
--edge_buffer_valid 1 
--valid_box_rescale_frac 1 
--alpha_scaling 1 
--show_labels 0`

The model successfully slices the images and does inference but I can't find the resulting image with the predictions as sees in the README. The only image file I have is one called '00_colormap_legend.png' which looks like as follows:
![img](https://user-images.githubusercontent.com/32295036/51799332-ac420980-2239-11e9-859d-b11d85074754.png)

Could anyone tell me why the image with the predictions made by the model wasn't generated?

Edit: Terminal output

```
1999 / 2000 
validate id: /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46/Satellite_AUH_split/Satellite_AUH__6846_0_544_544_0_17967_13205.png
2000 / 2000 
validate id: /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46/Satellite_AUH_split/Satellite_AUH__6846_2445_544_544_0_17967_13205.png
Total Detection Time: 57.93788 Seconds
"
Length of time to run command:  ./yolt/darknet -i 0 yolt2 valid /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46/logs/ave_dense.cfg /raid/local/src/simrdwn/results/train_yolt_dense_buildings_2019_01_16_07-05-19/ave_dense_20000_tmp.weights null 0 0.0 null /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46 /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46/valid_splitims_input_files.txt building 1 3 /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46/logs/yolt_loss.txt 0.15  2>&1 | tee -a /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46/logs/valid_yolt_dense_buildings_2019_01_27_09-31-46.log for 0 cutouts: 60.2704069614 seconds
"
valid_file: /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46/building.txt
Augmenting dataframe of initial length: 69 ...
removing bad idxs: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 42, 43, 44, 45, 46, 49, 50, 51, 52, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
Time to augment dataframe of length: 7 = 0.0232398509979 seconds
"Length of time to run valid for 6 files = 94.0050060749 seconds
"
validation data sliced? True
Plotting at: 0.2
Running refine_df()...
Inintial length: 7 Final length: 0
Time to run refine_df(): 0.00775718688965 seconds
Running plot_refined_df...
Time to run plot_refined_df(): 0.0173439979553 seconds
"Length of time to run refine_valid() 0.0269501209259 seconds
"
Removing valid_split_dir_tmp: /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46/Davis_Monthan_AFB_20180814_split/
Removing image chips...
Removing valid_split_dir_tmp: /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_27_09-31-46/Satellite_AUH_split/
Removing image chips...
"Length of time to run valid 94.1890370846 seconds
"

No honeymoon. This is business.
```

**Comment by avanetten** [comment]
The output of the log file shows that you are running inference on 6 files, rather than 2 as claimed.  That might be one issue.  Another is that it looks like your "min_retain_prob" is too high , as all the detected objects are being removed:

    Augmenting dataframe of initial length: 69 ...
    removing bad idxs: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 42, 43, 44, 45, 46, 49, 50, 51, 52, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]

This could be an issue with with the trained model, or the variance between train and test images could be too high.
