### ISSUE TITLE
ModuleNotFoundError: No module named 'yolt_data_prep_funcs' ?

### ISSUE THREAD

**Issue by ibrahimLearning** [avanetten/simrdwn#33]
I am try to use parse_cows.py for my owndata. when I run the following command
python /simrdwn/core/parse_cowc.py, it gives the following error:

Traceback (most recent call last):
  File "/simrdwn/simrdwn/core/parse_cowc.py", line 28, in <module>
    import yolt_data_prep_funcs
ModuleNotFoundError: No module named 'yolt_data_prep_funcs'

Is there any clue or idea about this error please?

**Comment by avanetten** [comment]
That module somehow didn't make the most recent push.  yolt_data_prep_funcs.py is up now.

**Comment by ibrahimLearning** [comment]
Thanks a lot 




K. M. lbrahim Khalilullah
PhD Student



E-mail: ibrahim_5403@yahoo.com
Cell Phone: +81-70-2250-7871

--------------------------------------------
On Thu, 4/25/19, Adam Van Etten <notifications@github.com> wrote:

 Subject: Re: [avanetten/simrdwn] ModuleNotFoundError: No module named 'yolt_data_prep_funcs' ? (#33)
 To: "avanetten/simrdwn" <simrdwn@noreply.github.com>
 Cc: "ibrahimLearning" <ibrahim_5403@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, April 25, 2019, 4:09 AM
 
 That module somehow didn't
 make the most recent push.  yolt_data_prep_funcs.py is up
 now.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
