### ISSUE TITLE
Would you explain please, how can I make label file for the splitted images?

### ISSUE THREAD

**Issue by ibrahimLearning** [avanetten/simrdwn#34]
I am going to train with my own dataset. My dataset is similar to yolov2. How can I get label of the a sliced image like cowc. As told before, it is similar to yolov2, therefore the slice_im() function is ok for me, but this function does not give labels's values for training.

**Comment by Smoothing97** [comment]
https://github.com/ringringyi/DOTA_YOLOv2/tree/master/data_transform
maybe this is working for you.Welcome message.

**Comment by avanetten** [comment]
Follow the description in: https://medium.com/the-downlinq/giving-simrdwn-a-spin-part-i-7032d7bf120a.  In brief, functions within simrdwn/core/parse_cowc.py will make labels for chipped images.
