### ISSUE TITLE
calculating detection rate using validation data?

### ISSUE THREAD

**Issue by ibrahimLearning** [avanetten/simrdwn#37]
I successfully trained my own dataset using SIMRDWN. The detection result is good (assumption from detected images). Thanks @avanetten and others for their help.
Now I want to calculate detection rate and non-detection rate (other performance metric) using validation data. Is there any suggestion please?
Currently I used yolt2 as your documentation. How can I use yolt3?

Thanks

**Comment by sbmalik** [comment]
Could you please elaborate the method for the validation of simrdwn?
