### ISSUE TITLE
Training Issues about all layer training and stopbackward command?

### ISSUE THREAD

**Issue by ibrahimLearning** [avanetten/simrdwn#39]
@avanetten When I use your command for training (in training mode for yolt2) as per your documentation, Is it training all layers or only head?

If only head, then how can I train all layers?

Thanks for your help

**Comment by ibrahimLearning** [comment]
@avanetten I have one more question please. How can I use "stopbackward" command in yolt2 and yolt3?

Thanks for your help

**Comment by avanetten** [comment]
Training is on all layers, and you'll have to provide more details on what you want with "stopbackward."

**Comment by ibrahimLearning** [comment]
@avanetten Thanks god! its solved. Just use yolt3 and read this fork:  https://github.com/AlexeyAB/darknet
