### ISSUE TITLE
question about how to generate the appropriate cutout of the large image

### ISSUE THREAD

**Issue by timbryant** [avanetten/simrdwn#4]
Hey,avanetten
 Sorry to trouble you again. I have trained the network, but the network didn't work, and I know where the question is. I use the whole large image as the input of the network, so the network didn't work. I read the paper again, and the papaer said the input should be the appropriate cutout of the large image.
The ''ReadMe.md" said :simrdwn/core/parse_cowc.py extracts training windows of reasonable size (usually 416 or 544 pixels in extent) from large labeleled images of the COWC dataset. but I didn't find the command to extract the windows. Could you tell me how to generate the appropriate cutout from the large image and the training windows should overlap or not,please?
Thank you very  much and look forward to your replying

**Comment by slash-fury** [comment]
@timbryant See my answer in the other topic; after reading the parse_cowc.py file, the comment at the end of the file shows a sample usage that you likely want to try using (i.e. calling parse_cowc directly). Overlap isn't a huge deal for training data, I think, but I generated my data just like inference with 20% overlap, which means that I'll likely have some repeat samples in my training data.

**Comment by SheInk** [comment]
@slash-fury it seems like parse_cowc.py just generate the list, it does not extract the training windows. Can you please help?

**Comment by avanetten** [comment]
Take a look at https://github.com/avanetten/simrdwn/blob/master/core/prep_data_cowc.py, hopefully this will provide everything you need prepare training data
