### ISSUE TITLE
xView Dataset slicing

### ISSUE THREAD

**Issue by mseals1** [avanetten/simrdwn#41]
Will one of your functions properly slice the xView images as well as the geojson label file and keep them in tact for training? I have been reading the code and trying to come up with a solution for awhile now, but I haven't found one yet. The xView dataset is different that COWC since each bounding box is a different size for each object.

Any help or pointers would be greatly appreciated!

**Comment by Gastennui** [comment]
The xview dataset publishers have created an entire set of utilities to read the geojson, slice it, and augment it (if you want). It can be found here: https://github.com/DIUx-xView/data_utilities

**Comment by mseals1** [comment]
Thank you so much for letting me know. This will hopefully solve my issue!
