### ISSUE TITLE
install error of the Updated SIMRDWN?

### ISSUE THREAD

**Issue by ibrahimLearning** [avanetten/simrdwn#42]
I installed previously before 2 months, it was fine. but when again try to make updated yolt2 and yolt3, it gives the following error:
`obj/gemm.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:65: recipe for target 'darknet' failed
make: *** [darknet] Error 1`
Would you give suggestion please, Thanks

**Comment by shie0041** [comment]
I see you closed this the next day. Did you find a solution?

**Comment by ibrahimLearning** [comment]
@shie0041 
Yes it is solved. sorry to say that I forgot what I did. Maybe that was nothing but clean and make command!
Thanks

**Comment by shie0041** [comment]
You're right, make clean did the trick. Thanks!
