### ISSUE TITLE
AVG value is very high during training yolt3?

### ISSUE THREAD

**Issue by ibrahimLearning** [avanetten/simrdwn#43]
The simrdwn is training with my own dataset (Sliced image size 544,544), but the avg values are very bad, like,
`71: 1480.305054, 1145.447998 avg, 0.000000 rate, 3.784609 seconds, 4544 images
Batch Num: 72 / 40000
72: 1478.472290, 1178.750488 avg, 0.000000 rate, 3.987175 seconds, 4608 images
Batch Num: 73 / 40000
73: 1487.111450, 1209.586548 avg, 0.000000 rate, 4.056619 seconds, 4672 images
Batch Num: 74 / 40000
74: 1490.246704, 1237.652588 avg, 0.000000 rate, 4.085837 seconds, 4736 images
Batch Num: 75 / 40000
75: 1499.956299, 1263.882935 avg, 0.000000 rate, 4.212585 seconds, 4800 images
Batch Num: 76 / 40000
76: 1506.523926, 1288.146973 avg, 0.000000 rate, 4.010417 seconds, 4864 images
Batch Num: 77 / 40000
77: 1469.643677, 1306.296631 avg, 0.000000 rate, 3.884122 seconds, 4928 images
Batch Num: 78 / 40000
78: 1539.585449, 1329.625488 avg, 0.000000 rate, 3.926301 seconds, 4992 images
Batch Num: 79 / 40000
79: 1497.862549, 1346.449219 avg, 0.000000 rate, 4.035428 seconds, 5056 images
Batch Num: 80 / 40000
80: 1490.782104, 1360.882568 avg, 0.000000 rate, 3.947680 seconds, 5120 images
Batch Num: 81 / 40000
81: 1478.097534, 1372.604004 avg, 0.000000 rate, 3.813151 seconds, 5184 images
Batch Num: 82 / 40000
`

My training command:

`python3 /simrdwn2/simrdwn/core/simrdwn.py \
	--framework yolt3 \
	--mode train \
	--outname dense_3class_vehicles \
	--yolt_cfg_file yolov3_544.cfg  \
	--weight_dir /simrdwn2/simrdwn/yolt3/input_weights \
	--weight_file yolov3.weights \
	--yolt_train_images_list_file stone_yolt_train_list.txt \
	--label_map_path /simrdwn2/simrdwn/data/class_labels_stone.pbtxt \
	--nbands 3 \
	--max_batches 40000 \
	--batch_size 64 \
	--subdivisions 16 \
	--gpu 0`

Would you give some advice please? I am waiting for your kind response. Thanks

**Comment by avanetten** [comment]
It seems likely that the training is not converging, possible due to an incorrectly formatted dataset, but I cannot be sure without more details

**Comment by ibrahimLearning** [comment]
@avanetten Thanks for your answer. However, finally the avg is reduced to ~1.7, after 30000 iteration.
However, If the avg value is higher as I mentioned before, what can I do? What does it mean "incorrectly formatted dataset"?

Thanks

**Comment by avanetten** [comment]
Longer training at times can help.  It's hard to deduce the reason for non-convergence without more information about your training dataset

**Comment by isgursoy** [comment]
One thing is not clear here, @ibrahimLearning why did you train stock yolo with yolt3 code? @avanetten what yolt3 code does without ave_dense.cfg? Does only code help small object detection? Paper=cfg, right?

**Comment by isgursoy** [comment]
Please see #57.

**Comment by ibrahimLearning** [comment]
@isgursoy 
I am sorry  I don't understand your term "stock yolo"

**Comment by isgursoy** [comment]
Yolo3 network structure without modifications.

**Comment by xjddavid** [comment]
I got similar output for the first 30 iteration. What does the rate mean here, why it is always 0.000000

**Comment by isgursoy** [comment]
This project is just bullshit, don't waste your time dude.
