### ISSUE TITLE
Low Average Loss without any detection!

### ISSUE THREAD

**Issue by MhmdDimassi** [avanetten/simrdwn#44]
I have trained my network on my own data, using yolt2.
My data consist of  200 labeled images of building,
At the end of the training, the average loss attend the interval [0.7,1.5], which is considered acceptable as first step.
During test time, i have test a lot of images but without any detection (without any box!).
Note that all tested images was from training set, so i expected a good result.
NOTE: i have select the threshold to 0, but this don't change the result.

TRAIN COMMAND:
python /simrdwn/core/simrdwn.py \
	--framework yolt2 \
	--mode train \
	--outname BUILDING \
	--yolt_cfg_file ave_dense.cfg  \
	--weight_dir /simrdwn/yolt2/input_weights \
	--weight_file yolo.weights \
	--yolt_train_images_list_file ImagesList.txt \
	--label_map_path /simrdwn/data/class_labels_building.pbtxt \
	--nbands 3 \
	--max_batches 10000 \
	--batch_size 2 \
	--subdivisions 1 \
	--gpu 0

TEST COMMAND:
python /simrdwn/core/simrdwn.py \
	--framework yolt \
	--mode test \
	--outname BUILDING \
        --label_map_path '/simrdwn/data/class_labels_building.pbtxt' \--train_model_path 'train_yolt2_BUILDING_2019_06_11_07-50-01' \
	--weight_file ave_dense_final.weights \
	--yolt_cfg_file ave_dense.cfg \
	--testims_dir 'images'  \
	--keep_test_slices 0 \
	--test_slice_sep __ \
	--test_make_legend_and_title 0 \
	--edge_buffer_test 1 \
	--test_box_rescale_frac 1 \
	--plot_thresh_str 0 \
	--slice_sizes_str 416 \
	--slice_overlap 0.2 \
	--alpha_scaling 1 \
	--show_labels 1

Example of Result:
![F4__0_6972_416_416_0_9351_9351](https://user-images.githubusercontent.com/42188224/59349822-3b504980-8d23-11e9-997c-40c12d90f25e.png)
![F4__0_7304_416_416_0_9351_9351](https://user-images.githubusercontent.com/42188224/59349823-3b504980-8d23-11e9-9b32-4d3c888e22f7.png)
![F4__0_7636_416_416_0_9351_9351](https://user-images.githubusercontent.com/42188224/59349824-3b504980-8d23-11e9-8f08-3e41fde4c49d.png)

Does any one have an idea for the solution?
Thank you!!

**Comment by avanetten** [comment]
Can you print the output of the test command?

**Comment by MhmdDimassi** [comment]
Thanks for quick response!!
Yes, This is the output, 
it include an error but after the segmentation and detection process, so i don't try to fix it in the current position,

Output:

Permit me to introduce myself...


SIMRDWN now...

Date string: 2019_06_12_20-20-05

Args: Namespace(BGR2RGB=0, alpha_scaling=1, append_date_string=1, batch_size=32, boxes_per_grid=5, building_csv_file='', date_string='2019_06_12_20-20-05', dpi=300, edge_buffer_test=1, extension_list=['.png', '.tif', '.TIF', '.TIFF', '.tiff', '.JPG', '.jpg', '.JPEG', '.jpeg'], figsize=(12, 12), framework='yolt', gpu=0, inference_graph_path2='/raid/local/src/simrdwn2/outputs/ssd/output_inference_graph/frozen_inference_graph.pb', inference_graph_path_tot='/simrdwn/results/train_yolt2_BUILDING_2019_06_12_14-21-27/frozen_model/frozen_inference_graph.pb', keep_test_slices=False, label_map_dict={1: 'Building'}, label_map_dict_rev={'Building': 1}, label_map_dict_rev_tot={'Building': 1}, label_map_dict_tot={1: 'Building'}, label_map_path='/simrdwn/data/class_labels_building.pbtxt', label_map_path2='', labels_log_file='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/logs/labels_list.txt', log_dir='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/logs', log_file='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/logs/test_yolt_BUILDING_2019_06_12_20-20-05.log', max_batches=60000, max_edge_aspect_ratio=3, min_retain_prob=0.025, mode='test', multi_band_delim='#', n_test_output_plots=10, nbands=3, nms_overlap_thresh=0.5, now=datetime.datetime(2019, 6, 12, 20, 20, 5, 813402), outname='BUILDING', overwrite_inference_graph=0, plot_line_thickness=2, plot_thresh=array([0.01]), plot_thresh_str='0.01', plot_thresh_str2='0.3', res_name='test_yolt_BUILDING_2019_06_12_20-20-05', results_dir='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05', results_topdir='/simrdwn/results', rotate_boxes=False, save_json=1, show_labels=1, show_test_plots=0, shuffle_val_output_plot_ims=0, simrdwn_dir='/simrdwn', single_gpu_machine=0, slice_overlap=0.2, slice_sizes=array([416]), slice_sizes2=[], slice_sizes_str='416', slice_sizes_str2='0', src_dir='/simrdwn/core', str_delim=',', subdivisions=4, test_add_geo_coords=True, test_box_rescale_frac=1.0, test_im_compression_level=6, test_ims_list=['F4.tif'], test_make_legend_and_title=False, test_prep_only=0, test_presliced_list='', test_presliced_list_tot='/simrdwn/results/', test_presliced_tfrecord_part='', test_presliced_tfrecord_tot='', test_slice_sep='__', test_splitims_locs_file='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/test_splitims_input_files.txt', test_splitims_locs_file_root='test_splitims_input_files.txt', test_splitims_locs_file_root2='test_splitims_input_files2.txt', test_tfrecord_out='', testims_dir='test', testims_dir_tot='/simrdwn/test', tf_cfg_train_file='/simrdwn/results/train_yolt2_BUILDING_2019_06_12_14-21-27/', tf_cfg_train_file_out='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/', tf_model_output_directory='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/frozen_model', tf_plot_file='/simrdwn/core/tf_plot_loss.py', this_file='/simrdwn/core/simrdwn.py', train_data_dir='/simrdwn/train_data', train_input_height=416, train_input_width=416, train_model_path='train_yolt2_BUILDING_2019_06_12_14-21-27', train_model_path2='', train_tf_record='', train_val_tf_record='', use_CUDNN=1, use_GPU=1, use_opencv='1', use_tfrecords=1, val_df_path_aug='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/test_predictions_aug.csv', val_df_path_init='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/test_predictions_init.csv', val_df_path_tot='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/test_predictions_tot.csv', val_df_root_aug='test_predictions_aug.csv', val_df_root_aug2='test_predictions_aug2.csv', val_df_root_init='test_predictions_init.csv', val_df_root_init2='test_predictions_init2.csv', val_df_root_tot='test_predictions_tot.csv', val_prediction_df_refine_tot='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/test_predictions_refine_thresh=0.01', val_prediction_df_refine_tot_root_part='test_predictions_refine', weight_dir='/raid/local/src/simrdwn2/yolt/input_weights', weight_dir2='/raid/local/src/simrdwn2/yolt/input_weights', weight_file='ave_17x17_final.weights', weight_file2='', weight_file_tot='/simrdwn/results/train_yolt2_BUILDING_2019_06_12_14-21-27/ave_17x17_final.weights', yolov3_filters=10, yolt_cfg_dir='/simrdwn/yolt/cfg', yolt_cfg_file='ave_17x17.cfg', yolt_cfg_file2='yolo.cfg', yolt_cfg_file_in='/simrdwn/results/train_yolt2_BUILDING_2019_06_12_14-21-27/logs/ave_17x17.cfg', yolt_cfg_file_tot='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/logs/ave_17x17.cfg', yolt_classnum=1, yolt_dir='/simrdwn/yolt', yolt_final_output=30, yolt_loss_file='/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/logs/yolt_loss.txt', yolt_nms_thresh=0.0, yolt_object_labels=['Building'], yolt_object_labels_str='Building', yolt_plot_file='/simrdwn/core/yolt_plot_loss.py', yolt_test_classes_files=['/simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/Building.txt'], yolt_train_images_list_file='', yolt_train_images_list_file_tot='/simrdwn/train_data/', yolt_weight_dir='/simrdwn/yolt/input_weights', zero_frac_thresh=0.5)

log_dir: /simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/logs

label_map_dict_tot: {1: 'Building'}
yolt_object_labels: ['Building']
yolt_classnum: 1
Prepping test files
Splitting test files...
test_ims_list: ['F4.tif']

1 / 1
test_file: F4.tif
test_dir: test_split_dir: /simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/F4_split/
Read in image: /simrdwn/test/F4.tif
image.shape: (9351, 9351, 3)
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
Num slices: 841 Num non-null slices: 837 sliceHeight 416 sliceWidth 416
Time to slice /simrdwn/test/F4.tif 22.723127603530884 seconds
Num files: 783
Total len test files: 783
test_splitims_locs_file: /simrdwn/results/test_yolt_BUILDING_2019_06_12_20-20-05/test_splitims_input_files.txt

Length of time to split test files: 25.470131158828735 seconds
Creating args.inference_graph_path_tot: /simrdwn/results/train_yolt2_BUILDING_2019_06_12_14-21-27/frozen_model/frozen_inference_graph.pb ...
Removing /simrdwn/results/train_yolt2_BUILDING_2019_06_12_14-21-27/frozen_model/saved_model so we can overwrite it...
Traceback (most recent call last):
  File "/simrdwn/core/simrdwn.py", line 2232, in <module>
    main()
  File "/simrdwn/core/simrdwn.py", line 2224, in main
    execute(args)
  File "/simrdwn/core/simrdwn.py", line 1658, in execute
    tf_cfg_train_file=args.tf_cfg_train_file)
  File "/simrdwn/core/simrdwn.py", line 585, in tf_export_model_cmd
    num_max_tmp = np.max(nums_tmp)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2505, in amax
    initial=initial)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by avanetten** [comment]
Looks like the issue is in the test command, which should say:
--framework yolt2
rather than:
--framework yolt 
The newest version of simrdwn should catch this in the future.

**Comment by MhmdDimassi** [comment]
Yes this is!
Thank you for your response,
I can see the difference when i change "--framework yolt" to "--framework yolt2".
But i have another question, according to my new output (of testing) the number of boxes regarding thresh x was greater than 0 (62),
and all boxes was saved in the file "result/test_yolt2_...../Building.txt" but i don't find any output images contain this boxes.
Note that an error exist in my output, and this is the last lines of  test command:


test_file: /simrdwn/results/test_yolt2_buillding_2019_06_17_10-26-18/building.txt
Augmenting dataframe of initial length: 415 ...
0
  set image path, make sure the image exists...
  add in global location of each row
removing bad idxs near junctions: [0, 21, 97, 139, 181, 223, 265, 307, 349, 391, 414]
Time to augment dataframe of length: 404 = 0.1346416473388672 seconds
Length of time to run test for 1 files = 3.227782726287842 seconds

test data sliced? True
Plotting at: 0.01
Running refine_df()...
Executing non-max suppression...
  non-max suppression init boxes: 404
  non-max suppression final boxes: 61
Initial length: 404 Final length: 61
Time to run refine_df(): 0.010788917541503906 seconds
Running plot_refined_df...
color_dict: {'airplane': (0, 255, 0), 'boat': (0, 0, 255), 'car': (255, 255, 0), 'airport': (255, 155, 0), 'building': (0, 0, 200)}
img_loc: /simrdwn/test2/2.png
  cv2: image.shape: (416, 416, 3)
Time to run plot_refined_df(): 0.22100377082824707 seconds
Num objects at thresh: 0.01 = 61
Traceback (most recent call last):
  File "/simrdwn/core/simrdwn.py", line 2232, in <module>
    main()
  File "/simrdwn/core/simrdwn.py", line 2224, in main
    execute(args)
  File "/simrdwn/core/simrdwn.py", line 1895, in execute
    json.to_file(output_json_path, driver="GeoJSON")
AttributeError: 'list' object has no attribute 'to_file'
