### ISSUE TITLE
Example YOLT format?

### ISSUE THREAD

**Issue by iboates** [avanetten/simrdwn#45]
Could you provide an example of the YOLT format? It says that they have to be relative to the image's width and height but I am wondering which coordinate exactly is supposed to be the x and y. Is it the bottom-left? Or potentially the top-left?

And if it is the top-left, is the height specified in the negative, similar to how rows & cols are defined differently to cartesian x & y?

Thanks

**Comment by avanetten** [comment]
Coordinates are for the bounding box centroid.  See https://pjreddie.com/darknet/yolo/ and  https://github.com/avanetten/simrdwn/blob/master/core/yolt_data_prep_funcs.py

**Comment by iboates** [comment]
Ok so I looked at these functions and I am having a hard time putting them together since I can't find a working example given a set of tif and geojson files, but I already wrote some snippets which are able to map the polygons to a bounding box and create a bounding box, so maybe you could just help me by clarifying a bit further:

Do you mean that the the x and y values correspond the the centroid, and that the width and height correspond to the total width and height of the polygon or just from the centroid to the outer edge?

i.e. given this image: https://i.imgur.com/1wh0luY.png

Where the white space around the pink polygon represents the bounding box, should the "width" of the feature be the length of the red line or the red line plus the blue line?
