### ISSUE TITLE
Limitation about the number of test images?

### ISSUE THREAD

**Issue by ibrahimLearning** [avanetten/simrdwn#47]
@avanetten Sorry for opening such type of issue.
I am facing a new problem with simrdwn for testing. I have 100 images in the test_images folder, but it always detect only 10 images.

Would you tell me please why it is happening?

**Comment by avanetten** [comment]
This is a feature.  There are many argument options in the main() function in simrdwn.py that are worth checking prior to assuming a bug.  In this case: 
parser.add_argument('--n_test_output_plots', type=int, default=10) 
sets the maximum number of outputs to plot.
