### ISSUE TITLE
When training: ModuleNotFoundError: No module named 'object_detection'

### ISSUE THREAD

**Issue by iboates** [avanetten/simrdwn#49]
I am using the SpaceNet Khartoum building training dataset. After wrangling all the data together I believe that I am ready to begin training, but I immediately ran into this error:

```
(simrdwn2) root@769ca72c93be:/# Traceback (most recent call last):
  File "/tensorflow/models/research/object_detection/model_main.py", line 25, in <module>
    from object_detection import model_hparams
ModuleNotFoundError: No module named 'object_detection
```

I was wondering if perhaps this is an indicator of having missed a crucial step early on. The command that I ran was as follows:

```
python /simrdwn/simrdwn/core/simrdwn.py \
	--framework ssd \
	--mode train \
	--outname kartoum_buildings \
	--label_map_path /simrdwn_data/pbtext/buildings.pbtxt \
	--tf_cfg_train_file /simrdwn/tf/cfg/_altered_v0/ssd_inception_v2_simrdwn.config \
	--train_tf_record /simrdwn_data/tfrecord/labels_building_train.tfrecord \
	--max_batches 30000 \
	--batch_size 16 
```

(I mounted a second directory called `simrdwn_data` to the container as I wanted to keep my data directly separate from the original repo directory).

The full output can be found [here](https://pastebin.com/ccMSQnTU). I put it on a pastebin so as not to clog up this page.

It seems as though it may be related to [this issue](https://github.com/tensorflow/models/issues/2031) on the tensorflow repo. But the suggested fixes appear to already be present in this repo's (SIMRDWN's) dockerfile.

**Comment by avanetten** [comment]
Looks like the module paths weren't set.  Try running Line 21 in the Dockerfile: 
export PYTHONPATH=$PYTHONPATH:/tensorflow/models/research/:/tensorflow/models/research/slim

**Comment by iboates** [comment]
Thanks, that seems to have fixed it.

**Comment by Jayanth1812** [comment]
I am getting the following errors, when I run the main training program..
(tensorflow) C:\tensorflow\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
File "train.py", line 54, in
from object_detection.builders import model_builder
File "C:\tensorflow\models\research\object_detection\builders\model_builder.py", line 20, in
from object_detection.builders import anchor_generator_builder
File "C:\tensorflow\models\research\object_detection\builders\anchor_generator_builder.py", line 23, in
from object_detection.anchor_generators import flexible_grid_anchor_generator
ModuleNotFoundError: No module named 'object_detection.anchor_generators'
