### ISSUE TITLE
UnsatisfiableError while installing using Dockerfile

### ISSUE THREAD

**Issue by jacquesmats** [avanetten/simrdwn#52]
I'm receiving this error while using the Dockerfile to set up:

`Step 19/35 : RUN conda install -n simrdwn2 	              affine 	              pyproj 	              pyhamcrest=1.9.0 	              cython 			  contextlib2 	              fiona 	              h5py 	              ncurses 	              jupyter 	              jupyterlab 	              ipykernel 	              libgdal 	              matplotlib 				  ncurses 	              numpy 	              pandas 	              pillow 	              pip 	              scipy 	              scikit-image               scikit-learn 	              shapely 	              gdal 	              rtree 	              testpath 	              tqdm 	              pandas 	              geopandas 	              rasterio 			  opencv=4.0.0 	&& conda clean -p 	&& conda clean -t 	&& conda clean --yes --all
 ---> Running in 95a5ece3e54e
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - fiona -> gdal[version='>=2.4.1,<2.5.0a0']
  - gdal
  - geopandas -> fiona -> gdal[version='>=2.4.1,<2.5.0a0']
  - numpy-base -> blas==1.0=mkl
  - opencv=4.0.0 -> blas==1.1=openblas

The command '/bin/bash -c conda install -n simrdwn2 	              affine 	              pyproj 	              pyhamcrest=1.9.0 	              cython 		  contextlib2 	              fiona 	              h5py 	              ncurses 	              jupyter 	              jupyterlab 	              ipykernel 	              libgdal 	              matplotlib 				  ncurses 	              numpy 	              pandas 	              pillow 	              pip 	              scipy 	              scikit-image               scikit-learn 	              shapely 	              gdal 	              rtree 	              testpath 	              tqdm 	              pandas 	              geopandas 	              rasterio 			  opencv=4.0.0 	&& conda clean -p 	&& conda clean -t 	&& conda clean --yes --all' returned a non-zero code: 1
`

Seem to be an incompatibility in the conda channels. Any ideas?

**Comment by iboates** [comment]
I just got this exact error today after i did a fresh reinstall of nvidia-docker and simrdwn (was having problems with CUDA drivers). I'm glad to see I am not the only one.

**Comment by jshermeyer** [comment]
Separate but potentially related issue when building the dockerfile:

InvalidArchiveError('Error with archive /opt/conda/pkgs/termcolor-1.1.0-py36_1.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nChild process exited with status 127 (errno=-1, retcode=-30, archive_p=93841327534592)')

The command '/bin/bash -c source activate simrdwn2 &&     conda install -n simrdwn2 -c defaults tensorflow-gpu=1.13.1' returned a non-zero code: 1

**Comment by jacquesmats** [comment]
I solve it temporarily using pip. I installed fiona and geopandas using pip and commented inside the conda command. Replace lines from 106 until 145 in the Dockerfile by:

```
RUN pip install fiona geopandas

RUN conda install -n simrdwn2 \
	              #awscli \
	              affine \
	              pyproj \
	              pyhamcrest=1.9.0 \
	              cython \
				  contextlib2 \
	              #fiona \
	              h5py \
	              ncurses \
	              jupyter \
	              jupyterlab \
	              ipykernel \
	              libgdal \
	              matplotlib \
				  ncurses \
	              numpy \
	              #opencv=3.4.1 \
	              #py-opencv \
	              pandas \
	              pillow \
	              pip \
	              scipy \
	              scikit-image \
	              scikit-learn \
	              shapely \
	              #gdal \
	              rtree \
	              testpath \
	              tqdm \
	              pandas \
	              #geopandas \
	              rasterio \
				  opencv=4.0.0 \
	&& conda clean -p \
	&& conda clean -t \
	&& conda clean --yes --all 
````

I mean temporarily because I don't know how it can affect the code in the future.

**Comment by avanetten** [comment]
gdal is the most brittle package I have ever encountered.  I combined conda channels (default and conda-forge) because that was the only way I could successfully install gdal a couple weeks ago.  Of course now, that seems to no longer be the case.  

@jacquesmats, the pip install command will likely work for another ~2 weeks before another update renders it useless again.  I'll work on pinning exact dependencies in future releases, but in the meantime my apologies for the frustration.

**Comment by iboates** [comment]
> gdal is the most brittle package I have ever encountered.

Truer words never spoken 😂 I don't think I've ever had a smooth experience with a GDAL install
