### ISSUE TITLE
Missing packages when building container using temporary fix

### ISSUE THREAD

**Issue by iboates** [avanetten/simrdwn#54]
I am trying to rebuild and run the container after applying the fixes in https://github.com/avanetten/simrdwn/issues/52 and https://github.com/avanetten/simrdwn/issues/53. I went to compile yolo2 and yolo3 but it just told me `make: Nothing to be done for 'all'.`

When I tried to run `simrdwn.py`, I got the error `ModuleNotFoundError: No module named 'statsmodels'`. I tried installing this package and was then immediately met with the same error, only this time complaining about missing `osgeo`. I thought these packages should have been installed when the image was built? Or has the temporary fix proposed by @jacquesmats already out of date?

**Comment by jacquesmats** [comment]
Hey @iboates. I suggest you implement just the fix #53, since it will prevent #52. About the make error, it is because you already use make before, and it is already compiled. 

> When I tried to run simrdwn.py, I got the error ModuleNotFoundError: No module named 'statsmodels'. I tried installing this package and was then immediately met with the same error, only this time complaining about missing osgeo. I thought these packages should have been installed when the image was built? Or has the temporary fix proposed by @jacquesmats already out of date?

I used to see this error when I was not inside the docker container, please make sure to be in it.

**Comment by avanetten** [comment]
The updated dockerfile should contain everything you need.
