### ISSUE TITLE
How can i download the datasets? the  COWC web was 404?

### ISSUE THREAD

**Issue by younkun** [avanetten/simrdwn#56]
https://gdo152.llnl.gov/cowc/]
when i visit this website

404. That’s an error.

The requested URL /datasetsearch was not found on this server. That’s all we know.

**Comment by jacquesmats** [comment]
Hey @younkun!

you should you wget:

```
Data located at:
    https://gdo152.llnl.gov/cowc/
    cd /raid/data/
    wget -r -np  ftp://gdo152.ucllnl.org/cowc/datasets/ground_truth_sets
```

**Comment by younkun** [comment]
Thank you for your help!!@jacquesmats
