### ISSUE TITLE
What does YOLT3 code?

### ISSUE THREAD

**Issue by isgursoy** [avanetten/simrdwn#57]
What does yolt3 code without ave_dense.cfg? Does code help small object detection alone?
You are proposing a network structure in your paper and you use stock yolo cfg in your blog post.
Also what is the difference between using ave_dense and ave_standard?

**Comment by ibrahimLearning** [comment]
@isgursoy 
ave_dense and ave_standard are configuration files. I can not think more than this. You may create your own configuration file by changing  parameters properly.

**Comment by isgursoy** [comment]
Thanks. But you and author use yolo3 cfg. Why?

**Comment by avanetten** [comment]
A configuration file is required, yolo3.cfg is the default option if YOLT3 is being used.

**Comment by isgursoy** [comment]
So to get your results in your paper and blogs one should use ave_dense with yolt code. Not yolo cfg with yolt code right?

Then why do you use yolo3 cfg in your blog?

What are the difference between dense and standard?

We have no result at 40K iterations.

**Comment by isgursoy** [comment]
Plus what yolt3 code changes exactly?

**Comment by isgursoy** [comment]
@avanetten
