### ISSUE TITLE
Object-class for YOLT training data

### ISSUE THREAD

**Issue by xjddavid** [avanetten/simrdwn#72]
In the readme of this repo, it is said "Class integers should be 1-indexed in the .pbtxt file." The train_data examples of this repo are indeed 1-indexed. However in the blog https://medium.com/the-downlinq/giving-simrdwn-a-spin-part-i-7032d7bf120a it is said that "Object-class is a zero-indexed integer." I think for native yolo training, the class index starts from 0 also. So which one I should use? I have tried 1-indexed for my multi-class detection case, and I think the prediction results seems mismatched.

**Comment by avanetten** [comment]
yolo requires 0-indexing, while tensorflow requires 1-indexing.  The latest version of SIMRDWN accounts for this, so you should 1-index the .pbtxt file, as stated in the readme
