### ISSUE TITLE
The yolt2/darknet run and stop after a few seconds

### ISSUE THREAD

**Issue by hmchuong** [avanetten/simrdwn#78]
I'm training the model with Yolt2 but the model is stuck after a few seconds. I use nvidia-smi and I saw a process `yolt2/darknet` running in a few seconds, after that it stops at this step
```
...
Num images = 32,
i= 0
N ims: 6165
Num iters: 30000
Loaded: 0.514691 seconds
Batch Num: 1 / 30000
```
I use the below command to run:
```
python simrdwn/core/simrdwn.py \
        --framework yolt2 \
        --mode train \
        --gpu 0 \
        --outname person \
        --yolt_cfg_file ave_dense.cfg  \
        --weight_file yolo.weights \
        --train_data_dir /simrdwn/data/cam_t5_new \
        --yolt_train_images_list_file train_list_short.txt \
        --label_map_path camt5_labels.pbtxt \
        --max_batches 30000 \
        --batch_size 32 \
        --subdivisions 16
```
I'm training on my own dataset and I have sliced big images to 416x416 ones

**Comment by jacquesmats** [comment]
@hmchuong How did you solve the problem?

**Comment by sunyuxiu** [comment]
You can try without of '--train_data_dir /simrdwn/data/cam_t5_new \' which '--yolt_train_images_list' contains the images which needed images catalog.Looking forward to your testing. @hmchuong @jacquesmats
