### ISSUE TITLE
Running inference in satellite imagery with model trained in Tensorflow object detection API

### ISSUE THREAD

**Issue by Geo-Trackers** [avanetten/simrdwn#8]
Dear Avanetten, 

First of all, cheers for such an amazing work. I have trained my model directly in Tensorflow Object Detection API, without using SIMRDWN.  
Can i use that frozen inference graph, and clone this SIMRDWN repository to run inference in very high resolution digital globe imagery or i need to explicitly train my model in SIMRDWN to run inference ?

Thank you. I look forward to hear from you.

Best Regards, 

Suman

**Comment by Geo-Trackers** [comment]
My task is to run inference in very high resolution satellite imagery ( ~67 km2 around 250 million pixels). How much dedicated GPU would you recommend for this purpose?

I eagerly await response from SIMRDWN Team.

Best, 

Suman

**Comment by Geo-Trackers** [comment]
You can use Gdal2tiles script in GDAL, and inside you will find a lot of image tiles in png format. After you have selected your specific image tiles consisting your objects. Simply download LabelImg, and upload images ( in png) to LabelImg and start creating your annotation. This will create your png and associated xml. (PS: you can work with png for training in Tensorflow, SIMRDWN might support png too.)

However, I am quite disappointed with the inactivity of this group.

**Comment by jian3xiao** [comment]
> You can use Gdal2tiles script in GDAL, and inside you will find a lot of image tiles in png format. After you have selected your specific image tiles consisting your objects. Simply download LabelImg, and upload images ( in png) to LabelImg and start creating your annotation. This will create your png and associated xml. (PS: you can work with png for training in Tensorflow, SIMRDWN might support png too.)
> 
> However, I am quite disappointed with the inactivity of this group.

Thanks a lot ! I will try. Perhaps there are few researchers who detect objects in remote sensing image using deep learning.

**Comment by Geo-Trackers** [comment]
Please let me know how SIMRDWN works. I haven't tried using it. I am applying Tensorflow object detection API and specifically faster_rcnn_resnet101_kitti model. I am implementing the link below to run final detection by generating tiles first and running inference over entire tiles.

Below, is a nice documentation and scripts for doing so:
https://github.com/developmentseed/label-maker/blob/master/examples/walkthrough-tensorflow-object-detection.md

Likewise, since there are not much researchers applying deep learning in remote sensing images, lets share our progress, so we could all learn together.

Thanks a lot

**Comment by ash1995** [comment]
Hey so I have tiled jpg images and the annotations in the appropriate format. How can I generate the training_list.txt file? I understand that it's the list of images and their locations. I was thinking of generating it manually so I just wanted to confirm what the format was.

Is the training_data_list.txt format like this:

Name of img        Img Location
Img1                     path/to/img1
Img2                     path/to/img2

**Comment by avanetten** [comment]
The slice_im_cowc() function within parse_cowc.py will tile large TIFF images into jpg or png format for training purposes.

**Comment by Ramanmagar** [comment]
which method i use for save crop images into tiff or geojson format. please any deep learning method suggest.

Thank you..
