### ISSUE TITLE
train my own dataset, the format of label

### ISSUE THREAD

**Issue by ssunlin** [avanetten/simrdwn#82]
hello,@avanetten
I want to train my own dataset, but I don't want to download the COWC dataset because of big size. I wonder what's the format of labels when executing the yolt2 model.
my dataset format is like this: 
images/0.jpg
images/0.txt  (the label in txtfile is :cls_id, x, y, w, h )
when I execute the yolt2 model, it looks normal, while the accuracy, precision and recall is NAN. So I want to know what's the label format in the txtfile.
![Screenshot from 2019-09-24 20-31-41](https://user-images.githubusercontent.com/17522209/65511764-79f0c500-df0a-11e9-8db1-747543ffbe01.png)

**Comment by jacquesmats** [comment]
I guess you are running out of images for training. It looks like you have 623 images, and this NaN problem start right after epoch 623.

**Comment by sunyuxiu** [comment]
Hello! How you change the your datasets to the net work needed?I having been puzzled this questions for a long time and did not find any way to work it out.

> hello,@avanetten
> I want to train my own dataset, but I don't want to download the COWC dataset because of big size. I wonder what's the format of labels when executing the yolt2 model.
> my dataset format is like this:
> images/0.jpg
> images/0.txt (the label in txtfile is :cls_id, x, y, w, h )
> when I execute the yolt2 model, it looks normal, while the accuracy, precision and recall is NAN. So I want to know what's the label format in the txtfile.
> ![Screenshot from 2019-09-24 20-31-41](https://user-images.githubusercontent.com/17522209/65511764-79f0c500-df0a-11e9-8db1-747543ffbe01.png)

**Comment by edwardnguyen1705** [comment]
Hi @sunyuxiu 
Have you found solution?

**Comment by sunyuxiu** [comment]
@edwardnguyen1705 Yes,it is maybe need the picture and the list name of picture,the bounding boxes of yolo format also needed.Which step do you on?Training or testing?

**Comment by edwardnguyen1705** [comment]
@sunyuxiu I already prepared anything. But my image size is 320x320 (actual size 1600x600, but I cropped patches 320x320, and transform the box coordinates to 320x320). I trained yolov5 on this dataset, there is no problem.

**Comment by sunyuxiu** [comment]
@edwardnguyen1705 yolov5 can support the hug size of image?My image size is hug with 8000x6000 and the object is so small with around  10x30.With a lot of days of searching for the properly net work and find this net can support the hug size.But recently I meet a new error with this net work when testing.https://github.com/avanetten/simrdwn/issues/101.Can you look and help me?

**Comment by sunyuxiu** [comment]
@edwardnguyen1705 Now I am trying training the image under the format of tensorflow and building the docker.Do you have an good idea about the training the hug size of image as I mentioned above?yolo v5 or this net?

**Comment by edwardnguyen1705** [comment]
@sunyuxiu ,
I have not tried this one so I do not know. But yolov5 is not suitable for your task, it cannot detect multi-scale objects in an image.
