### ISSUE TITLE
Training polygonal shape in yolt3?

### ISSUE THREAD

**Issue by ibrahimLearning** [avanetten/simrdwn#84]
@avanetten 
Would you suggest me please how can I use annotated objects with polygon for training? That means, I want to train polygonal shape object , not rectangle.

In which part of your code will I change?

Thanks for your help

**Comment by avanetten** [comment]
Bounding boxes are deeply integrated into the SIMRDWN codebase, so I'd suggest using a different tool if polygons are required.
