### ISSUE TITLE
How can i get the train images with 0.3 gsd?

### ISSUE THREAD

**Issue by nmxnql** [avanetten/simrdwn#87]
I want to train the train images with 0.3 gsd like the paper said. And I have run the function rescale_ims() in the simrdwn-master/data_prep/yolt_data_prep_funcs.py ,but the test mAP is not 0.72 like the paper said, I get the 0.42 mAP. Could you please  tell me how to generate the train images with 0.3 gsd? Thank you very much.

**Comment by avanetten** [comment]
What training dataset are you using?  A different mAP is to be expected if you are using different data than what was used in the paper.

**Comment by nmxnql** [comment]
I train the original cowc datasets with 0.15 gsd and get 0.72 mAP when the slice size is 416, and get 0.92 mAP when the slice is 208. But when I run the rescale_ims() in the  simrdwn-master/data_prep/yolt_data_prep_funcs.py, I get 0.42 mAP iwhen the slice size is 416 and 0.50 mAP when the slice size is 208.  I can't get as good results as in the thesis. In your paper, the car mAP is 0.72 when the cowc gsd is 0.3 and the slice size is 416.I don't know why.

**Comment by nmxnql** [comment]
I train the original cowc datasets with 0.15 gsd and get 0.72 mAP, but when I run the rescale_ims() in the simrdwn-master/data_prep/yolt_data_prep_funcs.py to generate the  images with 0.3 gsd, I get 0.42 mAP.  In your paper, the car mAP is 0.72 when the cowc images' gsd is 0.3. I can't get as good results as in your paper.I don't know why.
