### ISSUE TITLE
train the cowc datasets with 0.3 gsd

### ISSUE THREAD

**Issue by nmxnql** [avanetten/simrdwn#88]
I train the original cowc datasets with 0.15 gsd and get 0.72 mAP, but when I run the rescale_ims() in the simrdwn-master/data_prep/yolt_data_prep_funcs.py to generate the images with 0.3 gsd, I get 0.42 mAP. In your paper, the car mAP is 0.72 when the cowc images' gsd is 0.3. I can't get as good results as in your paper.I don't know why.

**Comment by avanetten** [comment]
You'll have to retrain at 0.3 meter GSD as well.  The rescale_ims() function will only transform images to a different resolution.  If the model is trained at one resolution (0.15m) applying that model to a a different resolution (0.3m) the results will be poor.
