### ISSUE TITLE
Running inference in High Resolution GeoTiff

### ISSUE THREAD

**Issue by Geo-Trackers** [avanetten/simrdwn#9]
Dear Avanetten, 

My purpose behind detecting objects in satellite imagery is to collect its spatial location after detection. Therefore, i wanted to whether we can run inferences over the high resolution geotiff? Furthermore, i want to run inference in satellite imagery of around 90 km2 to detect my objects of interest, is it possible to detect objects over such large area using SIMRDWN?

Thanks a lot & Cheers for such an amazing work. Looking forward to hear from you.

Best, 
Suman

**Comment by Geo-Trackers** [comment]
Quite surprised and disheartened to see the inactivity in the posts. :(

**Comment by avanetten** [comment]
SIMRDWN is designed to run inference on images of arbitrary size, so 90 km2 should be no problem.
