### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'simrdwn_dir'

### ISSUE THREAD

**Issue by fcu-d0347516** [avanetten/simrdwn#93]
Hello ,I use the dataset form COWC and  have some problem  when i start training .Can you help me?  

python /home/jack/simrdwn-master/simrdwn/core/simrdwn.py \
    --framework yolt3 \
    --mode train \
    --outname dense_cowc \
    --yolt_object_labels_str car \
    --yolt_cfg_file yolt.cfg  \
    --weight_file /simrdwn/core/yolov3.weights \
    --yolt_train_images_list_file cowc_yolt_train_list.txt \
    --label_map_path /home/jack/simrdwn-master/data/class_labels_car.pbtxt \
    --max_batches 30000 \
    --batch_size 64 \
    --subdivisions 16 \
    --gpu 0

![image](https://user-images.githubusercontent.com/32485231/77044229-02ec4300-69fa-11ea-993d-7925b624e864.png)

**Comment by annalisasheehan** [comment]
Hi, I'm having the same issue, did you manage to fix?

**Comment by sunyuxiu** [comment]
Hi, this issues maybe can help you :https://github.com/avanetten/simrdwn/issues/96

**Comment by tnmygrwl** [comment]
the solution is to add a `--boxes_per_grid` flag that is divisible by 3 for yolt3 testing. Without that the `update_args` function just returns without any args so you get a `NoneType` error.
